### ISSUE TITLE
Easier random theme choice....

### ISSUE THREAD

**Issue by PySimpleGUI** [schlopp96/DocuPort_PSG#1]
Love the idea you've got going here!  Great project.

A couple of really quick suggestions that may or may not be of interest (i.e. feel free to ignore)

You can replace the random theme selection with these 2 lines:
```python
theme = rChoice(sg.theme_list())
sg.theme(theme)

```

Then later you can tell the user in your layout what the theme is in case they like it.  At the end of your layout:

```python
    [sg.Exit()],
    [sg.Text(f'Like the theme? It is {theme}', font='_ 8')],
```

https://github.com/schlopp96/DocuPort_PSG/blob/74cd3cb5bf2fae448d2de06b853b231c9988f43c/src/DocuPort_PSG.pyw#L176

**Comment by schlopp96** [comment]
Oh wow, that's certainly a much more elegant implementation than my method! Thank you so much for your suggestion! PySimpleGUI is a big part of what I love about Python! As a self-taught developer who's starting uni soon for CS, I really appreciate how much work you've put into PSG, and how much time and love has gone into it.

Again, love the suggestion! Thanks again!

**Comment by PySimpleGUI** [comment]
BTW, You're quite welcome, and thank you for the incredibly kind words.  Made my day/week!
